---
- hosts: devbdd
  become: true
  
  vars:
    mysql_root_pass: mypassword #MySQL Root Password

  tasks:
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes
    - name: Upgrade the OS (apt-get dist-upgrade)
      apt:
        upgrade: dist


    - name: Installation mysql-server
      apt:
        name: mysql-server
    - name: Install the MySQL packages
      apt: name={{ item }} 
      with_items:
        - mysql-server
        - mysql-client
        - python-mysqldb
        - libmysqlclient-dev

    - name: Update MySQL root password for all root accounts
      mysql_user: name=root  password={{ mysql_root_pass }} state=present


    - name: Download initial SQL file
      get_url:
        url: https://raw.githubusercontent.com/brichbourg/Multi-Tier-App-Demo/master/sql/create_db_table.sql
        dest: .

    - name: setting default root password
      mysql_user:
        name: root
        password: "{{ mysql_root_password }}"
        check_implicit_admin: true
        login_unix_socket: /var/run/mysqld/mysqld.sock
   
    - name: execute install.sh
      shell:
        cmd: mysql -u root -p root

    - name: Simple select query to appdemo db
      community.mysql.mysql_query:
        login_db: appdemo
        login_user: root
        login_password: "{{ mysql_root_password }}"
        query: 
        - INSERT INTO articles (id, story) VALUES (2, 'my_long_story')

#          - CREATE TABLE `demodata` (  `id` INTEGER NOT NULL AUTO_INCREMENT,  `name` VARCHAR(100),  `notes` TEXT,  `timestamp` TIMESTAMP,  PRIMARY KEY (`id`),  KEY (`name`)  )
#          - CREATE TABLE `demodata_erase_log` (  `id` INTEGER NOT NULL AUTO_INCREMENT,  `timestamp` TIMESTAMP,  PRIMARY KEY (`id`),  KEY (`timestamp`)  )
#          - CREATE USER 'appdemo'@'%' IDENTIFIED BY 'appdemo'
#          - GRANT ALL PRIVILEGES ON appdemo.* to 'appdemo'@'%' WITH GRANT OPTION
