---
- hosts: devweb
  become: true

  vars:
    ansible_python_interpreter: /usr/bin/python3


  tasks:


    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes
    - name: Upgrade the OS (apt-get dist-upgrade)
      apt:
        upgrade: dist



    - name: Git checkout
      git:
        repo: 'https://github.com/ilkilab/Multi-Tier-App-Demo.git'
        dest: ./Multi-Tier-App-Demo

    - name: Installation Apache2
      apt:
        name: apache2
        state: latest
      with_items:
        - { state: present, name: mpm_prefork }
        - { state: present, name: cgi }
        - { state: absent, name: mpm_event }
        
        
    - name: Gestion du service Apache2
      service:
        name: apache2
        state: started
        enabled: yes
        
    - name: Modification page de démarrage
      copy:
        src: ./www/index.html
        dest: /var/www/html/index.html

    - name: Installation python3-pip
      apt:
        name: python3-pip


    - name: Installation pymysql
      pip:
        name: pymysql



    - name: Download 000-default.conf
      get_url:
        url: https://s3.amazonaws.com/richbourg-s3/mtwa/web/000-default.conf
        dest: /etc/apache2/sites-enabled/
      notify:
        - Reload Apache 2
        
    - name: Download ports.conf
      get_url:
        url: https://s3.amazonaws.com/richbourg-s3/mtwa/web/ports.conf
        dest: /etc/apache2/
      notify:
        - Reload Apache 2



    - name: execute install.sh
      shell:
         cmd: /bin/bash install.sh
      args:
        chdir: ./Multi-Tier-App-Demo/

    notify:    
    - name: Reload Apache 2
      service:
        name: apache2
        state: reloaded         
