---
- hosts: devapp
  become: true

  vars:
    ansible_python_interpreter: /usr/bin/python3


  tasks:


    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes
    - name: Upgrade the OS (apt-get dist-upgrade)
      apt:
        upgrade: dist



    - name: Git checkout
      git:
        repo: 'https://github.com/ilkilab/Multi-Tier-App-Demo.git'
        dest: ./Multi-Tier-App-Demo

    - name: Installation Apache2
      apt:
        name: apache2
        state: latest
      with_items:
        - { state: present, name: mpm_prefork }
        - { state: present, name: cgi }
        - { state: absent, name: mpm_event }
        
        
    - name: Gestion du service Apache2
      service:
        name: apache2
        state: started
        enabled: yes
        
    - name: Modification page de démarrage
      copy:
        src: ./www/index.html
        dest: /var/www/html/index.html

    - name: Installation python3-pip
      apt:
        name: python3-pip


    - name: Installation pymysql
      pip:
        name: pymysql



    - name: Download 000-default.conf
      get_url:
        url: https://s3.amazonaws.com/richbourg-s3/mtwa/app/000-default.conf
        dest: /etc/apache2/sites-enabled/
      notify:
        - Reload Apache 2
        
    - name: Download ports.conf
      get_url:
        url: https://s3.amazonaws.com/richbourg-s3/mtwa/app/ports.conf
        dest: /etc/apache2/
      notify:
        - Reload Apache 2

    - name: Create a directory /etc/mtwa if it does not exist
      ansible.builtin.file:
        path: /etc/mtwa
        state: directory
        mode: '0755'
    - name: Create a directory /var/www/html/appdemo if it does not exist
      ansible.builtin.file:
        path: /var/www/html/appdemo
        state: directory
        mode: '0755'


    - name: execute install.sh
      shell:
         cmd: cp ~/Multi-Tier-App-Demo/mtwa.conf /etc/mtwa/mtwa.conf
    - name: execute install.sh
      shell:
         cmd: cp ~/Multi-Tier-App-Demo/html/* /var/www/html/appdemo/
    - name: execute install.sh
      shell:
         cmd: cp ~/Multi-Tier-App-Demo/scripts/* /var/www/html/appdemo/
         


  handlers:    
    - name: Reload Apache 2
      service:
        name: apache2
        state: reloaded         
