---
- hosts: Prodapp
  become: true
  
  vars:
    mysql_root_pass: mypassword #MySQL Root Password

  tasks:
   - name: Gestion du service mysql
     service:
        name: mysql
        state: started
        enabled: yes
     notify: 
       - name: restartMySql
          
  handlers:    
    - name: restartMySql    
      service:
        name: mysql
        state: restarted 
